**AIVLE School 미니프로젝트**
### **공공데이터를 활용한 <span style="color:darkgreen">미세먼지 농도</span> 예측**
---

#### **<span style="color:red">[미션 안내]</span>**
* 개인 미션: 미세먼지 농도를 예측하는 머신러닝 모델을 만드세요. <br> ([1-1]부터 [1-2]까지, [2-1]부터 [2-8]까지, [3-1]부터 [3-2]까지 필수 수행, [4-1]부터 선택 수행)
* 조별 미션: 개인 미션 수행한 내용에 대해 토론하여 발표 준비를 해주세요.

**학습 데이터**

**air_2021.csv : 2021년 미세먼지 데이터**

**weather_2021.csv : 2021년 날씨 데이터**

**테스트 데이터**

**air_2022.csv : 2022년 미세먼지 데이터**

**weather_2022.csv : 2022년 날씨 데이터**

In [ ]:
# 필요한 라이브러리 설치 및 임포트
!pip install pandas

import pandas as pd
import datetime

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

#### **<span style="color:blue">[1-1] air_21, air_22, weather_21, weather_22 데이터 로딩</span>**

In [ ]:
# 데이터 로딩

air_21 = pd.read_csv("/content/drive/MyDrive/미니프로젝트/2차_미세먼지 농도 예측, 장애인 콜택시 대기시간 예측 머신러닝 모델/2023.09.11_미니프로젝트2차_1일차 미세먼지 농도 예측/데이터/air_2021.csv")
air_22 = pd.read_csv("/content/drive/MyDrive/미니프로젝트/2차_미세먼지 농도 예측, 장애인 콜택시 대기시간 예측 머신러닝 모델/2023.09.11_미니프로젝트2차_1일차 미세먼지 농도 예측/데이터/air_2022.csv")
weather_21 = pd.read_csv("/content/drive/MyDrive/미니프로젝트/2차_미세먼지 농도 예측, 장애인 콜택시 대기시간 예측 머신러닝 모델/2023.09.11_미니프로젝트2차_1일차 미세먼지 농도 예측/데이터/weather_2021.csv", sep=',', encoding='cp949')
weather_22 = pd.read_csv("/content/drive/MyDrive/미니프로젝트/2차_미세먼지 농도 예측, 장애인 콜택시 대기시간 예측 머신러닝 모델/2023.09.11_미니프로젝트2차_1일차 미세먼지 농도 예측/데이터/weather_2022.csv", sep=',', encoding='cp949')

#### **<span style="color:blue">[1-2] 필요한 데이터 분석 진행 </span>**

In [ ]:
print(air_21.head())
print(air_21.info())
air_21.describe()

   Unnamed: 0      지역     망   측정소코드 측정소명        측정일시    SO2   CO     O3  \
0           0  서울 종로구  도시대기  111123  종로구  2021100101  0.003  0.6  0.002
1           1  서울 종로구  도시대기  111123  종로구  2021100102  0.003  0.6  0.002
2           2  서울 종로구  도시대기  111123  종로구  2021100103  0.003  0.6  0.002
3           3  서울 종로구  도시대기  111123  종로구  2021100104  0.003  0.6  0.002
4           4  서울 종로구  도시대기  111123  종로구  2021100105  0.003  0.5  0.003

     NO2  PM10  PM25                주소
0  0.039  31.0  18.0  서울 종로구 종로35가길 19
1  0.035  27.0  16.0  서울 종로구 종로35가길 19
2  0.033  28.0  18.0  서울 종로구 종로35가길 19
3  0.030  26.0  16.0  서울 종로구 종로35가길 19
4  0.026  26.0  16.0  서울 종로구 종로35가길 19
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  8760 non-null   int64
 1   지역          8760 non-null   object
 2   망           8760 non-null   object
 3   측정소코드       8760 non-null   int64
 4   측정소명        8760 non-null   object
 5   측정일시        8760 non-null   int64
 6   SO2         8648 non-null   float64
 7   CO          8680 non-null   float64
 8   O3          8663 non-null   float64
 9   NO2         8680 non-null   float64
 10  PM10        8655 non-null   float64
 11  PM25        8663 non-null   float64
 12  주소          8760 non-null   object
dtypes: float64(6), int64(3), object(4)
memory usage: 889.8+ KB
None

,Unnamed: 0,측정소코드,측정일시,SO2,CO,O3,NO2,PM10,PM25
count,8760.000000,8760.0,8.760000e+03,8648.000000,8680.000000,8663.000000,8680.000000,8655.000000,8663.000000
mean,4379.500000,111123.0,2.021067e+09,0.003385,0.505645,0.029246,0.023346,38.925361,20.466005
std,2528.938512,0.0,3.450216e+04,0.000826,0.209516,0.019708,0.014456,47.470577,16.564915
min,0.000000,111123.0,2.021010e+09,0.001000,0.200000,0.000000,0.003000,3.000000,1.000000
25%,2189.750000,111123.0,2.021040e+09,0.003000,0.400000,0.015000,0.012000,18.000000,10.000000
50%,4379.500000,111123.0,2.021070e+09,0.003000,0.400000,0.028000,0.019000,30.000000,16.000000
75%,6569.250000,111123.0,2.021100e+09,0.004000,0.600000,0.040000,0.031000,46.000000,25.000000
max,8759.000000,111123.0,2.021123e+09,0.011000,2.000000,0.137000,0.082000,942.000000,154.000000

In [ ]:
print(air_22.head())
print(air_22.info())
air_22.describe()

   Unnamed: 0      지역     망   측정소코드 측정소명        측정일시    SO2   CO     O3  \
0           0  서울 종로구  도시대기  111123  종로구  2022010101  0.003  0.4  0.026
1           1  서울 종로구  도시대기  111123  종로구  2022010102  0.003  0.4  0.022
2           2  서울 종로구  도시대기  111123  종로구  2022010103  0.003  0.5  0.014
3           3  서울 종로구  도시대기  111123  종로구  2022010104  0.003  0.5  0.016
4           4  서울 종로구  도시대기  111123  종로구  2022010105  0.003  0.5  0.005

     NO2  PM10  PM25                주소
0  0.016  23.0  12.0  서울 종로구 종로35가길 19
1  0.020  20.0   9.0  서울 종로구 종로35가길 19
2  0.028  20.0   9.0  서울 종로구 종로35가길 19
3  0.027  19.0  10.0  서울 종로구 종로35가길 19
4  0.040  24.0  11.0  서울 종로구 종로35가길 19
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  2160 non-null   int64
 1   지역          2160 non-null   object
 2   망           2160 non-null   object
 3   측정소코드       2160 non-null   int64
 4   측정소명        2160 non-null   object
 5   측정일시        2160 non-null   int64
 6   SO2         2139 non-null   float64
 7   CO          2139 non-null   float64
 8   O3          2139 non-null   float64
 9   NO2         2139 non-null   float64
 10  PM10        2122 non-null   float64
 11  PM25        2135 non-null   float64
 12  주소          2160 non-null   object
dtypes: float64(6), int64(3), object(4)
memory usage: 219.5+ KB
None

,Unnamed: 0,측정소코드,측정일시,SO2,CO,O3,NO2,PM10,PM25
count,2160.000000,2160.0,2.160000e+03,2139.000000,2139.000000,2139.000000,2139.000000,2122.000000,2135.000000
mean,1079.500000,111123.0,2.022022e+09,0.003385,0.576718,0.024673,0.027864,40.563148,27.288993
std,623.682612,0.0,8.347462e+03,0.000708,0.201352,0.014215,0.015426,23.480890,18.614884
min,0.000000,111123.0,2.022010e+09,0.002000,0.300000,0.002000,0.005000,3.000000,1.000000
25%,539.750000,111123.0,2.022012e+09,0.003000,0.400000,0.012000,0.015000,26.000000,15.000000
50%,1079.500000,111123.0,2.022021e+09,0.003000,0.500000,0.026000,0.024000,36.000000,22.000000
75%,1619.250000,111123.0,2.022031e+09,0.004000,0.700000,0.035000,0.040000,49.000000,35.000000
max,2159.000000,111123.0,2.022033e+09,0.006000,1.400000,0.074000,0.074000,239.000000,121.000000

In [ ]:
print(weather_21.head())
print(weather_21.info())
weather_21.describe()

    지점 지점명                일시  기온(°C)  기온 QC플래그  강수량(mm)  강수량 QC플래그  풍속(m/s)  \
0  108  서울  2021-01-01 01:00    -8.7       NaN      NaN        NaN      2.4
1  108  서울  2021-01-01 02:00    -9.1       NaN      NaN        NaN      1.6
2  108  서울  2021-01-01 03:00    -9.3       NaN      NaN        NaN      1.1
3  108  서울  2021-01-01 04:00    -9.3       NaN      NaN        NaN      0.3
4  108  서울  2021-01-01 05:00    -9.7       NaN      NaN        NaN      1.9

   풍속 QC플래그  풍향(16방위)  ...  최저운고(100m )  시정(10m)  지면상태(지면상태코드)  현상번호(국내식)  \
0       NaN     270.0  ...          NaN     2000           NaN        NaN
1       NaN     270.0  ...          NaN     2000           NaN        NaN
2       NaN     250.0  ...          NaN     2000           NaN        NaN
3       NaN       0.0  ...          NaN     2000           NaN        NaN
4       NaN      20.0  ...          NaN     2000           NaN        NaN

   지면온도(°C)  지면온도 QC플래그  5cm 지중온도(°C)  10cm 지중온도(°C)  20cm 지중온도(°C)  \
0      -6.9         NaN          -1.0           -0.8            0.3
1      -7.1         NaN          -1.1           -0.8            0.3
2      -7.3         NaN          -1.2           -0.9            0.3
3      -7.5         NaN          -1.3           -1.0            0.2
4      -7.6         NaN          -1.3           -1.0            0.2

   30cm 지중온도(°C)
0            1.6
1            1.6
2            1.6
3            1.5
4            1.5

[5 rows x 38 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8759 entries, 0 to 8758
Data columns (total 38 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   지점             8759 non-null   int64
 1   지점명            8759 non-null   object
 2   일시             8759 non-null   object
 3   기온(°C)         8759 non-null   float64
 4   기온 QC플래그       0 non-null      float64
 5   강수량(mm)        949 non-null    float64
 6   강수량 QC플래그      1763 non-null   float64
 7   풍속(m/s)        8757 non-null   float64
 8   풍속 QC플래그       2 non-null      float64
 9   풍향(16방위)       8757 non-null   float64
 10  풍향 QC플래그       2 non-null      float64
 11  습도(%)          8759 non-null   int64
 12  습도 QC플래그       0 non-null      float64
 13  증기압(hPa)       8759 non-null   float64
 14  이슬점온도(°C)      8759 non-null   float64
 15  현지기압(hPa)      8759 non-null   float64
 16  현지기압 QC플래그     0 non-null      float64
 17  해면기압(hPa)      8759 non-null   float64
 18  해면기압 QC플래그     0 non-null      float64
 19  일조(hr)         4791 non-null   float64
 20  일조 QC플래그       3968 non-null   float64
 21  일사(MJ/m2)      4791 non-null   float64
 22  일사 QC플래그       3968 non-null   float64
 23  적설(cm)         379 non-null    float64
 24  3시간신적설(cm)     29 non-null     float64
 25  전운량(10분위)      8757 non-null   float64
 26  중하층운량(10분위)    8759 non-null   int64
 27  운형(운형약어)       4947 non-null   object
 28  최저운고(100m )    4547 non-null   float64
 29  시정(10m)        8759 non-null   int64
 30  지면상태(지면상태코드)   0 non-null      float64
 31  현상번호(국내식)      2125 non-null   float64
 32  지면온도(°C)       8754 non-null   float64
 33  지면온도 QC플래그     24 non-null     float64
 34  5cm 지중온도(°C)   8754 non-null   float64
 35  10cm 지중온도(°C)  8754 non-null   float64
 36  20cm 지중온도(°C)  8754 non-null   float64
 37  30cm 지중온도(°C)  8754 non-null   float64
dtypes: float64(31), int64(4), object(3)
memory usage: 2.5+ MB
None

,지점,기온(°C),기온 QC플래그,강수량(mm),강수량 QC플래그,풍속(m/s),풍속 QC플래그,풍향(16방위),풍향 QC플래그,습도(%),...,최저운고(100m ),시정(10m),지면상태(지면상태코드),현상번호(국내식),지면온도(°C),지면온도 QC플래그,5cm 지중온도(°C),10cm 지중온도(°C),20cm 지중온도(°C),30cm 지중온도(°C)
count,8759.0,8759.000000,0.0,949.000000,1763.0,8757.000000,2.0,8757.000000,2.0,8759.000000,...,4547.000000,8759.000000,0.0,2.125000e+03,8754.000000,24.00000,8754.000000,8754.000000,8754.000000,8754.000000
mean,108.0,13.739194,NaN,1.250263,9.0,2.311328,9.0,169.658559,9.0,65.589223,...,15.161425,1719.765384,NaN,1.367177e+04,14.734304,1.87500,15.128581,14.555118,14.533276,14.827633
std,0.0,10.894786,NaN,3.398801,0.0,1.120906,0.0,107.549684,0.0,18.394276,...,13.537921,521.130959,NaN,4.170156e+05,12.042066,3.73366,10.175582,10.044423,9.739277,9.360493
min,108.0,-18.500000,NaN,0.000000,9.0,0.000000,9.0,0.000000,9.0,19.000000,...,1.000000,33.000000,NaN,1.000000e+00,-12.700000,0.00000,-4.700000,-4.600000,-3.000000,-0.800000
25%,108.0,6.000000,NaN,0.000000,9.0,1.500000,9.0,50.000000,9.0,51.000000,...,7.000000,1719.000000,NaN,5.000000e+00,4.300000,0.00000,5.900000,5.500000,5.600000,6.300000
50%,108.0,14.600000,NaN,0.100000,9.0,2.200000,9.0,200.000000,9.0,66.000000,...,10.000000,2000.000000,NaN,1.900000e+01,15.400000,0.00000,15.400000,14.700000,14.600000,15.100000
75%,108.0,22.600000,NaN,1.100000,9.0,2.900000,9.0,270.000000,9.0,80.000000,...,16.000000,2000.000000,NaN,1.901000e+03,23.600000,0.00000,24.100000,23.500000,23.400000,23.600000
max,108.0,36.300000,NaN,64.700000,9.0,8.300000,9.0,360.000000,9.0,100.000000,...,76.000000,2000.000000,NaN,1.916020e+07,56.800000,9.00000,35.700000,33.700000,31.900000,30.600000

In [ ]:
print(weather_22.head())
print(weather_22.info())
weather_22.describe()

    지점 지점명                일시  기온(°C)  기온 QC플래그  강수량(mm)  강수량 QC플래그  풍속(m/s)  \
0  108  서울  2022-01-01 00:00    -8.5       NaN      NaN        NaN      1.9
1  108  서울  2022-01-01 01:00    -9.2       NaN      NaN        NaN      1.8
2  108  서울  2022-01-01 02:00    -9.5       NaN      NaN        NaN      1.2
3  108  서울  2022-01-01 03:00    -9.3       NaN      NaN        NaN      1.4
4  108  서울  2022-01-01 04:00    -9.6       NaN      NaN        NaN      1.7

   풍속 QC플래그  풍향(16방위)  ...  최저운고(100m )  시정(10m)  지면상태(지면상태코드)  현상번호(국내식)  \
0       NaN       320  ...          NaN     2000           NaN        NaN
1       NaN       270  ...          NaN     2000           NaN        NaN
2       NaN       270  ...          NaN     2000           NaN        NaN
3       NaN       290  ...          NaN     2000           NaN        NaN
4       NaN       340  ...          NaN     2000           NaN        NaN

   지면온도(°C)  지면온도 QC플래그  5cm 지중온도(°C)  10cm 지중온도(°C)  20cm 지중온도(°C)  \
0      -7.0         NaN          -1.0           -1.0           -0.2
1      -7.2         NaN          -1.1           -1.1           -0.2
2      -7.5         NaN          -1.3           -1.2           -0.2
3      -7.6         NaN          -1.4           -1.2           -0.2
4      -7.6         NaN          -1.4           -1.3           -0.3

   30cm 지중온도(°C)
0            1.0
1            1.0
2            1.0
3            1.0
4            1.0

[5 rows x 38 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 38 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   지점             2160 non-null   int64
 1   지점명            2160 non-null   object
 2   일시             2160 non-null   object
 3   기온(°C)         2160 non-null   float64
 4   기온 QC플래그       0 non-null      float64
 5   강수량(mm)        81 non-null     float64
 6   강수량 QC플래그      382 non-null    float64
 7   풍속(m/s)        2160 non-null   float64
 8   풍속 QC플래그       0 non-null      float64
 9   풍향(16방위)       2160 non-null   int64
 10  풍향 QC플래그       0 non-null      float64
 11  습도(%)          2160 non-null   int64
 12  습도 QC플래그       0 non-null      float64
 13  증기압(hPa)       2160 non-null   float64
 14  이슬점온도(°C)      2160 non-null   float64
 15  현지기압(hPa)      2160 non-null   float64
 16  현지기압 QC플래그     0 non-null      float64
 17  해면기압(hPa)      2160 non-null   float64
 18  해면기압 QC플래그     0 non-null      float64
 19  일조(hr)         1071 non-null   float64
 20  일조 QC플래그       1089 non-null   float64
 21  일사(MJ/m2)      1071 non-null   float64
 22  일사 QC플래그       1089 non-null   float64
 23  적설(cm)         140 non-null    float64
 24  3시간신적설(cm)     15 non-null     float64
 25  전운량(10분위)      2160 non-null   int64
 26  중하층운량(10분위)    2160 non-null   int64
 27  운형(운형약어)       939 non-null    object
 28  최저운고(100m )    743 non-null    float64
 29  시정(10m)        2160 non-null   int64
 30  지면상태(지면상태코드)   0 non-null      float64
 31  현상번호(국내식)      418 non-null    float64
 32  지면온도(°C)       2160 non-null   float64
 33  지면온도 QC플래그     7 non-null      float64
 34  5cm 지중온도(°C)   2160 non-null   float64
 35  10cm 지중온도(°C)  2160 non-null   float64
 36  20cm 지중온도(°C)  2160 non-null   float64
 37  30cm 지중온도(°C)  2160 non-null   float64
dtypes: float64(29), int64(6), object(3)
memory usage: 641.4+ KB
None

,지점,기온(°C),기온 QC플래그,강수량(mm),강수량 QC플래그,풍속(m/s),풍속 QC플래그,풍향(16방위),풍향 QC플래그,습도(%),...,최저운고(100m ),시정(10m),지면상태(지면상태코드),현상번호(국내식),지면온도(°C),지면온도 QC플래그,5cm 지중온도(°C),10cm 지중온도(°C),20cm 지중온도(°C),30cm 지중온도(°C)
count,2160.0,2160.000000,0.0,81.000000,382.0,2160.000000,0.0,2160.000000,0.0,2160.000000,...,743.000000,2160.000000,0.0,418.000000,2160.000000,7.0,2160.000000,2160.000000,2160.000000,2160.000000
mean,108.0,1.518148,NaN,1.392593,9.0,2.430231,NaN,212.856481,NaN,57.306481,...,12.454913,1737.135648,NaN,5578.363636,2.495093,0.0,2.196620,1.678241,1.673843,2.142685
std,0.0,6.358060,NaN,4.087321,0.0,1.164067,NaN,100.383875,NaN,17.524800,...,9.158550,488.601856,NaN,33784.324460,7.624066,0.0,4.069035,3.937891,3.706190,3.399132
min,108.0,-11.300000,NaN,0.000000,9.0,0.000000,NaN,0.000000,NaN,17.000000,...,2.000000,141.000000,NaN,1.000000,-10.500000,0.0,-2.400000,-2.400000,-1.400000,-0.300000
25%,108.0,-3.300000,NaN,0.000000,9.0,1.600000,NaN,160.000000,NaN,45.000000,...,7.000000,1721.750000,NaN,19.000000,-2.800000,0.0,-0.300000,-0.700000,-0.500000,0.000000
50%,108.0,1.200000,NaN,0.000000,9.0,2.300000,NaN,250.000000,NaN,55.000000,...,10.000000,2000.000000,NaN,19.000000,0.000000,0.0,0.200000,-0.300000,-0.400000,0.100000
75%,108.0,6.100000,NaN,0.900000,9.0,3.100000,NaN,270.000000,NaN,69.000000,...,14.000000,2000.000000,NaN,42.000000,7.000000,0.0,4.900000,4.500000,4.225000,3.825000
max,108.0,19.400000,NaN,32.200000,9.0,7.900000,NaN,360.000000,NaN,100.000000,...,60.000000,2000.000000,NaN,401905.000000,31.100000,0.0,13.100000,12.000000,11.000000,10.500000

# [Step 2] 데이터 전처리

#### **<span style="color:blue">[2-1] air_21, air_22 의 '측정일시'를 활용하여 'time' 변수 생성</span>**
* air_21, air_22  각각 '측정일시'를 활용하여 'time'변수 생성
    * 참고: 미세먼지 데이터는 1시-24시, 날씨 데이터는 0시-23시로 구성되어 있습니다.

In [ ]:
# air_21, air_22 각각 '측정일시'를 활용하여 'time'변수 생성
# time 변수를 pd.to_datetime으로 데이터 타입 변경

air_21['time'] = air_21['측정일시'] - 1
air_21['time'] = pd.to_datetime(air_21['time'], format='%Y%m%d%H')

air_21['time']

0      2021-10-01 00:00:00
1      2021-10-01 01:00:00
2      2021-10-01 02:00:00
3      2021-10-01 03:00:00
4      2021-10-01 04:00:00
               ...
8755   2021-09-30 19:00:00
8756   2021-09-30 20:00:00
8757   2021-09-30 21:00:00
8758   2021-09-30 22:00:00
8759   2021-09-30 23:00:00
Name: time, Length: 8760, dtype: datetime64[ns]

In [ ]:
air_22['time'] = air_22['측정일시'] - 1
air_22['time'] = pd.to_datetime(air_22['time'], format='%Y%m%d%H')

air_22['time']

0      2022-01-01 00:00:00
1      2022-01-01 01:00:00
2      2022-01-01 02:00:00
3      2022-01-01 03:00:00
4      2022-01-01 04:00:00
               ...
2155   2022-03-31 19:00:00
2156   2022-03-31 20:00:00
2157   2022-03-31 21:00:00
2158   2022-03-31 22:00:00
2159   2022-03-31 23:00:00
Name: time, Length: 2160, dtype: datetime64[ns]

#### **<span style="color:blue">[2-2] weather_21, weather_22 의 '일시'를 활용하여 'time' 변수 생성</span>**
* weather_21, weather_22 의 '일시'를 활용하여 'time'변수 생성
* time 변수를 pd.to_datetime으로 데이터 타입 변경

In [ ]:
weather_21['time'] = weather_21['일시']
weather_21['time'] = pd.to_datetime(weather_21['time'])

# 'weather_22'
weather_22['time'] = weather_22['일시']
weather_22['time'] = pd.to_datetime(weather_22['time'])
weather_21['time'].head()

0   2021-01-01 01:00:00
1   2021-01-01 02:00:00
2   2021-01-01 03:00:00
3   2021-01-01 04:00:00
4   2021-01-01 05:00:00
Name: time, dtype: datetime64[ns]

#### **<span style="color:blue">[2-3] 'time' 기준으로 데이터 합치기</span>**
* 미세먼지 데이터와 날씨 데이터를 'time' 기준으로 합쳐보세요.
    * df_21에는 'time' 기준으로 21년도 미세먼지, 날씨 데이터를 합쳐보세요.
    * df_22에는 'time' 기준으로 22년도 미세먼지, 날씨 데이터를 합쳐보세요.

In [ ]:
df_21 = pd.merge(air_21, weather_21, on='time', how='inner')

df_22 = pd.merge(air_22, weather_22, on='time', how='inner')

df_21

,Unnamed: 0,지역,망,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,...,최저운고(100m ),시정(10m),지면상태(지면상태코드),현상번호(국내식),지면온도(°C),지면온도 QC플래그,5cm 지중온도(°C),10cm 지중온도(°C),20cm 지중온도(°C),30cm 지중온도(°C)
0,0,서울 종로구,도시대기,111123,종로구,2021100101,0.003,0.6,0.002,0.039,...,NaN,2000,NaN,NaN,17.8,NaN,22.3,22.3,22.7,22.9
1,1,서울 종로구,도시대기,111123,종로구,2021100102,0.003,0.6,0.002,0.035,...,NaN,2000,NaN,NaN,17.4,NaN,22.1,22.0,22.5,22.9
2,2,서울 종로구,도시대기,111123,종로구,2021100103,0.003,0.6,0.002,0.033,...,NaN,2000,NaN,NaN,17.2,NaN,21.8,21.8,22.4,22.8
3,3,서울 종로구,도시대기,111123,종로구,2021100104,0.003,0.6,0.002,0.030,...,NaN,2000,NaN,NaN,17.0,NaN,21.6,21.6,22.2,22.8
4,4,서울 종로구,도시대기,111123,종로구,2021100105,0.003,0.5,0.003,0.026,...,NaN,2000,NaN,NaN,16.5,NaN,21.3,21.4,22.0,22.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8754,8755,서울 종로구,도시대기,111123,종로구,2021093020,0.003,0.7,0.020,0.036,...,NaN,2000,NaN,NaN,20.6,NaN,24.2,23.7,23.0,22.6
8755,8756,서울 종로구,도시대기,111123,종로구,2021093021,0.003,0.6,0.016,0.035,...,NaN,2000,NaN,NaN,19.9,NaN,23.7,23.4,23.1,22.8
8756,8757,서울 종로구,도시대기,111123,종로구,2021093022,0.003,0.6,0.012,0.036,...,NaN,2000,NaN,NaN,19.2,NaN,23.3,23.1,23.0,22.9
8757,8758,서울 종로구,도시대기,111123,종로구,2021093023,0.003,0.6,0.004,0.042,...,NaN,2000,NaN,NaN,18.6,NaN,23.0,22.8,22.9,22.9
8758,8759,서울 종로구,도시대기,111123,종로구,2021093024,0.003,0.6,0.003,0.042,...,NaN,2000,NaN,NaN,18.1,NaN,22.6,22.5,22.8,22.9

In [ ]:
df_21.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8759 entries, 0 to 8758
Data columns (total 52 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     8759 non-null   int64
 1   지역             8759 non-null   object
 2   망              8759 non-null   object
 3   측정소코드          8759 non-null   int64
 4   측정소명           8759 non-null   object
 5   측정일시           8759 non-null   int64
 6   SO2            8647 non-null   float64
 7   CO             8679 non-null   float64
 8   O3             8662 non-null   float64
 9   NO2            8679 non-null   float64
 10  PM10           8654 non-null   float64
 11  PM25           8662 non-null   float64
 12  주소             8759 non-null   object
 13  time           8759 non-null   datetime64[ns]
 14  지점             8759 non-null   int64
 15  지점명            8759 non-null   object
 16  일시             8759 non-null   object
 17  기온(°C)         8759 non-null   float64
 18  기온 QC플래그       0 non-null      float64
 19  강수량(mm)        949 non-null    float64
 20  강수량 QC플래그      1763 non-null   float64
 21  풍속(m/s)        8757 non-null   float64
 22  풍속 QC플래그       2 non-null      float64
 23  풍향(16방위)       8757 non-null   float64
 24  풍향 QC플래그       2 non-null      float64
 25  습도(%)          8759 non-null   int64
 26  습도 QC플래그       0 non-null      float64
 27  증기압(hPa)       8759 non-null   float64
 28  이슬점온도(°C)      8759 non-null   float64
 29  현지기압(hPa)      8759 non-null   float64
 30  현지기압 QC플래그     0 non-null      float64
 31  해면기압(hPa)      8759 non-null   float64
 32  해면기압 QC플래그     0 non-null      float64
 33  일조(hr)         4791 non-null   float64
 34  일조 QC플래그       3968 non-null   float64
 35  일사(MJ/m2)      4791 non-null   float64
 36  일사 QC플래그       3968 non-null   float64
 37  적설(cm)         379 non-null    float64
 38  3시간신적설(cm)     29 non-null     float64
 39  전운량(10분위)      8757 non-null   float64
 40  중하층운량(10분위)    8759 non-null   int64
 41  운형(운형약어)       4947 non-null   object
 42  최저운고(100m )    4547 non-null   float64
 43  시정(10m)        8759 non-null   int64
 44  지면상태(지면상태코드)   0 non-null      float64
 45  현상번호(국내식)      2125 non-null   float64
 46  지면온도(°C)       8754 non-null   float64
 47  지면온도 QC플래그     24 non-null     float64
 48  5cm 지중온도(°C)   8754 non-null   float64
 49  10cm 지중온도(°C)  8754 non-null   float64
 50  20cm 지중온도(°C)  8754 non-null   float64
 51  30cm 지중온도(°C)  8754 non-null   float64
dtypes: datetime64[ns](1), float64(37), int64(7), object(7)
memory usage: 3.5+ MB

#### **<span style="color:blue">[2-4] 사용하지 않을 변수 제거</span>**
* 머신러닝에 사용하지 않을 변수들을 제거

In [ ]:
# df_21, df_22에 사용할 변수들만 할당
selected_columns = ['time', 'PM10', 'PM25','SO2','CO','O3','NO2', '기온(°C)', '강수량(mm)','풍속(m/s)','습도(%)']
df_21 = df_21[selected_columns]
df_22 = df_22[selected_columns]

In [ ]:
# time 변수를 index로 세팅
df_21 = df_21.set_index('time').sort_index()
df_22 = df_22.set_index('time').sort_index()

df_21

,PM10,PM25,SO2,CO,O3,NO2,기온(°C),강수량(mm),풍속(m/s),습도(%)
time,,,,,,,,,,
2021-01-01 01:00:00,25.0,14.0,0.002,0.6,0.018,0.020,-8.7,NaN,2.4,68
2021-01-01 02:00:00,27.0,16.0,0.002,0.6,0.013,0.025,-9.1,NaN,1.6,69
2021-01-01 03:00:00,23.0,13.0,0.003,0.6,0.011,0.027,-9.3,NaN,1.1,70
2021-01-01 04:00:00,24.0,14.0,0.003,0.6,0.008,0.032,-9.3,NaN,0.3,71
2021-01-01 05:00:00,26.0,16.0,0.002,0.7,0.003,0.037,-9.7,NaN,1.9,72
...,...,...,...,...,...,...,...,...,...,...
2021-12-31 19:00:00,26.0,8.0,0.003,0.4,0.025,0.020,-6.4,NaN,2.2,34
2021-12-31 20:00:00,27.0,9.0,0.003,0.4,0.030,0.014,-6.3,NaN,4.1,35
2021-12-31 21:00:00,20.0,8.0,0.003,0.4,0.033,0.011,-6.7,NaN,4.8,36
2021-12-31 22:00:00,20.0,9.0,0.003,0.4,0.029,0.015,-7.5,NaN,3.0,37
2021-12-31 23:00:00,20.0,9.0,0.003,0.4,0.026,0.016,-7.7,NaN,2.9,38

In [ ]:
df_21.isnull().sum()

PM10        105
PM25         97
SO2         112
CO           80
O3           97
NO2          80
기온(°C)        0
강수량(mm)    7810
풍속(m/s)       2
습도(%)         0
dtype: int64

In [ ]:
df_22.isnull().sum()

PM10         38
PM25         25
SO2          21
CO           21
O3           21
NO2          21
기온(°C)        0
강수량(mm)    2079
풍속(m/s)       0
습도(%)         0
dtype: int64

In [ ]:
# df_21, df_22의 변수 중 결측치를 처리
df_21.drop(['강수량(mm)'], axis=1, inplace=True)
df_22.drop(['강수량(mm)'], axis=1, inplace=True)

In [ ]:
# 나머지 전날 값으로 결측치 채우기
df_21.fillna(method='ffill', inplace=True)
df_22.fillna(method='ffill', inplace=True)

In [ ]:
# df_21, df_22의 결측치 재확인
print(df_21.isnull().sum())
print(df_22.isnull().sum())

PM10       0
PM25       0
SO2        0
CO         0
O3         0
NO2        0
기온(°C)     0
풍속(m/s)    0
습도(%)      0
dtype: int64
PM10       0
PM25       0
SO2        0
CO         0
O3         0
NO2        0
기온(°C)     0
풍속(m/s)    0
습도(%)      0
dtype: int64

#### **<span style="color:blue">[2-6] 전일 같은 시간 미세먼지 농도 변수 추가</span>**

In [ ]:
# month, day, hour 변수를 추가
df_21['month'] = df_21.index.month
df_21['day'] = df_21.index.day
df_21['hour'] = df_21.index.hour

df_22['month'] = df_22.index.month
df_22['day'] = df_22.index.day
df_22['hour'] = df_22.index.hour

In [ ]:
#df_21, df_22에 전일 같은 시간 미세먼지 농도 변수(PM10_lag1) 추가

df_21['PM10_lag1'] = df_21['PM10'].shift(24)

df_22['PM10_lag1'] = df_22['PM10'].shift(24)

df_21

,PM10,PM25,SO2,CO,O3,NO2,기온(°C),풍속(m/s),습도(%),month,day,hour,PM10_lag1
time,,,,,,,,,,,,,
2021-01-01 01:00:00,25.0,14.0,0.002,0.6,0.018,0.020,-8.7,2.4,68,1,1,1,NaN
2021-01-01 02:00:00,27.0,16.0,0.002,0.6,0.013,0.025,-9.1,1.6,69,1,1,2,NaN
2021-01-01 03:00:00,23.0,13.0,0.003,0.6,0.011,0.027,-9.3,1.1,70,1,1,3,NaN
2021-01-01 04:00:00,24.0,14.0,0.003,0.6,0.008,0.032,-9.3,0.3,71,1,1,4,NaN
2021-01-01 05:00:00,26.0,16.0,0.002,0.7,0.003,0.037,-9.7,1.9,72,1,1,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-31 19:00:00,26.0,8.0,0.003,0.4,0.025,0.020,-6.4,2.2,34,12,31,19,24.0
2021-12-31 20:00:00,27.0,9.0,0.003,0.4,0.030,0.014,-6.3,4.1,35,12,31,20,31.0
2021-12-31 21:00:00,20.0,8.0,0.003,0.4,0.033,0.011,-6.7,4.8,36,12,31,21,28.0
2021-12-31 22:00:00,20.0,9.0,0.003,0.4,0.029,0.015,-7.5,3.0,37,12,31,22,29.0
2021-12-31 23:00:00,20.0,9.0,0.003,0.4,0.026,0.016,-7.7,2.9,38,12,31,23,23.0

#### **<span style="color:blue">[2-7] t+1 시점의 미세먼지 농도 데이터 생성</span>**
* t+1 시점은 1시간 후 입니다.
* t+1 시점의 미세먼지 농도 변수(PM10_1)를 생성.
* t+1 시점의 미세먼지 농도는 머신러닝 모델을 통해 예측하려는 y값(target)

In [ ]:
# df_21, df_22에 t+1 시점 변수(PM10_1) 추가
df_21['PM10_1'] = df_21['PM10'].shift(-1)
df_22['PM10_1'] = df_22['PM10'].shift(-1)

In [ ]:
# 결측치 이전 값으로 대체
df_21['PM10_1'].fillna(method='ffill', inplace=True)

df_22['PM10_1'].fillna(method='ffill', inplace=True)

df_21['PM10_lag1'].fillna(df_21['PM10'], inplace=True)

df_22['PM10_lag1'].fillna(df_22['PM10'], inplace=True)

In [ ]:
df_21.isnull().sum()

PM10         0
PM25         0
SO2          0
CO           0
O3           0
NO2          0
기온(°C)       0
풍속(m/s)      0
습도(%)        0
month        0
day          0
hour         0
PM10_lag1    0
PM10_1       0
dtype: int64

#### **<span style="color:blue">[2-8] train, test 데이터 분리</span>**

In [ ]:
train_x = df_21.drop(columns=['PM10_1'])
train_y = df_21['PM10_1']

test_x = df_22.drop(columns=['PM10_1'])
test_y = df_22['PM10_1']

In [ ]:
print(train_x.shape)
print(train_y.shape)
print(test_x.shape)
print(test_y.shape)

(8759, 13)
(8759,)
(2160, 13)
(2160,)

In [ ]:
print(train_x.info())
print(test_x.info())

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 8759 entries, 2021-01-01 01:00:00 to 2021-12-31 23:00:00
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   PM10       8759 non-null   float64
 1   PM25       8759 non-null   float64
 2   SO2        8759 non-null   float64
 3   CO         8759 non-null   float64
 4   O3         8759 non-null   float64
 5   NO2        8759 non-null   float64
 6   기온(°C)     8759 non-null   float64
 7   풍속(m/s)    8759 non-null   float64
 8   습도(%)      8759 non-null   int64
 9   month      8759 non-null   int64
 10  day        8759 non-null   int64
 11  hour       8759 non-null   int64
 12  PM10_lag1  8759 non-null   float64
dtypes: float64(9), int64(4)
memory usage: 958.0 KB
None
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2160 entries, 2022-01-01 00:00:00 to 2022-03-31 23:00:00
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   PM10       2160 non-null   float64
 1   PM25       2160 non-null   float64
 2   SO2        2160 non-null   float64
 3   CO         2160 non-null   float64
 4   O3         2160 non-null   float64
 5   NO2        2160 non-null   float64
 6   기온(°C)     2160 non-null   float64
 7   풍속(m/s)    2160 non-null   float64
 8   습도(%)      2160 non-null   int64
 9   month      2160 non-null   int64
 10  day        2160 non-null   int64
 11  hour       2160 non-null   int64
 12  PM10_lag1  2160 non-null   float64
dtypes: float64(9), int64(4)
memory usage: 236.2 KB
None

#[3-0] 머신러닝 모델링

In [ ]:
import pandas as pd
import numpy as np

from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
import joblib

**[3-1]모델링: LinearRegression**
* 성능지표 : MSE, R-squared Score(소수점 5째자리까지)

In [ ]:
model1 = LinearRegression()
model1.fit(train_x,train_y)

LinearRegression()

In [ ]:
pred1 = model1.predict(test_x)

In [ ]:
mse1 = mean_squared_error(test_y, pred1)
r2_1 = r2_score(test_y, pred1)

print(f'MSE: {mse1:.5f}')
print(f'R-squared Score: {r2_1:.5f}')

MSE: 37.12291
R-squared Score: 0.93280

In [ ]:
# 학습 성능
print('train score :', model1.score(train_x, train_y))

# 평가 성능
print('test score :', model1.score(test_x, test_y))

train score : 0.9649186836533055
test score : 0.9327966518917302

**[3-2]모델링: 랜덤포레스트**

In [ ]:
model2 = RandomForestRegressor()
model2.fit(train_x, train_y)

RandomForestRegressor()

In [ ]:
pred2 = model2.predict(test_x)

In [ ]:
mse2 = mean_squared_error(test_y, pred2)
r2_2 = r2_score(test_y, pred2)

print(f'MSE: {mse2:.5f}')
print(f'R-squared Score: {r2_2:.5f}')

MSE: 39.53665
R-squared Score: 0.92843

In [ ]:
# 학습 성능
print('train score :', model2.score(train_x, train_y))

# 평가 성능
print('test score :', model2.score(test_x, test_y))

train score : 0.9948154465336361
test score : 0.928427069450512

**[3-3]모델링: GradientBoosting**

In [ ]:
model3 = GradientBoostingRegressor(max_depth=5)
model3.fit(train_x,train_y)

GradientBoostingRegressor(max_depth=5)

In [ ]:
pred3 = model3.predict(test_x)

In [ ]:
mse3 = mean_squared_error(test_y, pred3)
r2_3 = r2_score(test_y, pred3)

print(f'MSE: {mse3:.5f}')
print(f'R-squared Score: {r2_3:.5f}')

MSE: 40.58027
R-squared Score: 0.92654

In [ ]:
# 학습 성능
print('train score :', model3.score(train_x, train_y))

# 평가 성능
print('test score :', model3.score(test_x, test_y))

train score : 0.9907749138693409
test score : 0.9265378044591512